config/routes.rb
Rails.application.routes.draw do
  root to: 'lists#index'
  resources :movies
  resources :lists, except: :index do
    resources :bookmarks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie
  validates :list_id, presence: true
  validates :movie_id, presence: true
  validates :comment, length: { minimum: 6 }
  validates_uniqueness_of :movie_id, scope: :list_id
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list

    if @bookmark.save
      redirect_to list_path(@list), notice: "Restaurant was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :list_id, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show edit update destroy]

  def index
    @lists = List.all
  end

  def show
  end

  def new
    @list = List.new
  end

  def edit
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to list_path(@list), notice: "list was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @list.update(list_params)
      redirect_to list_path(@list), notice: "list was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_url, notice: "list was successfully destroyed."
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: %i[show edit update destroy]

  def index
    @movies = Movie.all
  end

  def show
  end

  def new
    @movie = Movie.new
  end

  def edit
  end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      redirect_to movie_path(@movie), notice: "Movie was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @movie.update(movie_params)
      redirect_to movie_path(@movie), notice: "Movie was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @movie.destroy
    redirect_to movies_url, notice: "Movie was successfully destroyed."
  end

  private

  def set_movie
    @movie = Movie.find(params[:id])
  end

  def movie_params
    params.require(:movie).permit(:title, :overview, :poster_url, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for([@list, @bookmark]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :movie %>
  </div>
  <div class="form-inputs">
    <%= f.input :comment %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/bookmarks/new.html.erb
<div id="new_bookmark" class="container">
  <h1>New bookmark</h1>

  <%= render "form", bookmark: @bookmark %>

  <br>

  <div>
    <%= link_to "Back to lists", root_path %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/lists/_bookmarks.html.erb
<% @list.bookmarks.each do |bookmark|  %>
  <div class="col-sm-4 align-items-stretch ">
    <div class="card mb-2" style="width: 18rem;">
      <img src="" class="card-img-top" alt="...">
      <div class="card-body">
      <h5 class="card-title"><%= bookmark.movie.title %></h5>
      <p><%= bookmark.comment %></p>
    </div>
  </div>
<% end %>

app/views/lists/_form.html.erb
<%= simple_form_for(@list) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/lists/_list.html.erb
<div class="col-sm-4 d-flex align-items-stretch ">
  <div class="card mb-2" style="width: 18rem;">
    <img src="" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title"><%= list.name %></h5>
      <%= link_to "view list", list %>
    </div>
  </div>
</div>

app/views/lists/_listing.html.erb
<div class="row" id="lists">
  <% lists.each do |list| %>
    <%= render list %>
  <% end %>
</div>

app/views/lists/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://cdn.pixabay.com/photo/2016/01/22/08/17/banner-1155437_1280.png);">
  <div class="container">
    <h1>Save <strong>any kind</strong> of <strong>movies</strong>!</h1>
    <%# <p>Change your life and learn to code at one of our campuses around the world.</p> %>
    <p><span data-controller="typed-js"></span></p>
  </div>
</div>
<h1>Lists</h1>
<div class="container">
  <%= render 'listing', lists: @lists %>
</div>

app/views/lists/new.html.erb
<div id="new_list" class="container">
  <h1>New list</h1>

  <%= render "form", list: @list %>

  <br>

  <div>
    <%= link_to "Back to lists", root_path %>
  </div>
</div>

app/views/lists/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://cdn.pixabay.com/photo/2016/01/22/08/17/banner-1155437_1280.png);">

    <h1><%= @list.name %></h1>
    <%# <p>Change your life and learn to code at one of our campuses around the world.</p> %>
    <p><span data-controller="typed-js"></span></p>

</div>
<div class="container">
  <div class="row">
    <%= render 'bookmarks', bookmarks: @bookmarks %>
    <div>
      <p><%= link_to "Add a bookmark", new_list_bookmark_path(@list) %></p>
      <p><%= button_to "Destroy this list", @list, method: :delete %></p>
    </div>
  </div>
</div>

app/views/movies/_list.html.erb
<div class="row" id="movies">
  <% movies.each do |movie| %>
    <%= render movie %>
  <% end %>
</div>

app/views/movies/_movie.html.erb
<div class="col-sm-4 d-flex align-items-stretch ">
  <div class="card mb-2" style="width: 18rem;">
    <img src="<%= movie.poster_url %>" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title"><%= movie.title %></h5>
      <p class="card-text"><%= movie.overview %></p>
      <p class="card-text"><%= "⭐️" * movie.rating %></p>
      <a href="#" class="btn btn-primary">Bookmarks</a>
    </div>
  </div>
</div>

app/views/movies/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Movies</h1>
<div class="container">
  <%= render 'list', movies: @movies %>
</div>

app/views/movies/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @movie %>

<p><%= link_to 'Add a review', new_movie_review_path(@movie) %></p>

<ul>
  <% @movie.reviews.each do |review| %>
    <li>
      <%= review.content %>
      <%= link_to "Delete",
        review_path(review),
        data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
    </li>
  <% end %>
</ul>

<div>
  <p><%= link_to "Edit this movie", edit_movie_path(@movie) %></p>
  <p><%= link_to "Back to movies", movies_path %></p>
  <p><%= button_to "Destroy this movie", @movie, method: :delete %></p>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top"
     data-controller="navbar"
     data-action="scroll@window->navbar#updateNavbar">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <img src="https://img.freepik.com/premium-vector/cinema-camera-roll-film-logo-design-template_527727-210.jpg?w=2000" />
</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <%= link_to "My lists", root_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "New list", new_list_path, class:"nav-link" %>
          </li>
          <!--li class="nav-item"-->
          <!--/li-->
      </ul>
    </div>
  </div>
</div>